# Generated by Django 2.1.2 on 2018-10-05 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='boby',
            new_name='body',
        ),
    ]
